/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PhotographyRouteImport } from './routes/photography'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ActingRouteImport } from './routes/acting'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PhotographyIndexRouteImport } from './routes/photography.index'
import { Route as ActingIndexRouteImport } from './routes/acting.index'
import { Route as PhotographySectionRouteImport } from './routes/photography.$section'
import { Route as ActingProfileRouteImport } from './routes/acting.profile'
import { Route as ActingSectionRouteImport } from './routes/acting.$section'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ActingProjectsSlugRouteImport } from './routes/acting.projects.$slug'
import { Route as AuthenticatedAdminSiteRouteImport } from './routes/_authenticated/admin.site'
import { Route as AuthenticatedAdminProjectsRouteImport } from './routes/_authenticated/admin.projects'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin.media'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographyRoute = PhotographyRouteImport.update({
  id: '/photography',
  path: '/photography',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ActingRoute = ActingRouteImport.update({
  id: '/acting',
  path: '/acting',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographyIndexRoute = PhotographyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PhotographyRoute,
} as any)
const ActingIndexRoute = ActingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ActingRoute,
} as any)
const PhotographySectionRoute = PhotographySectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => PhotographyRoute,
} as any)
const ActingProfileRoute = ActingProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ActingRoute,
} as any)
const ActingSectionRoute = ActingSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => ActingRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ActingProjectsSlugRoute = ActingProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => ActingRoute,
} as any)
const AuthenticatedAdminSiteRoute = AuthenticatedAdminSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminProjectsRoute =
  AuthenticatedAdminProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acting': typeof ActingRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/photography': typeof PhotographyRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/acting/$section': typeof ActingSectionRoute
  '/acting/profile': typeof ActingProfileRoute
  '/photography/$section': typeof PhotographySectionRoute
  '/acting/': typeof ActingIndexRoute
  '/photography/': typeof PhotographyIndexRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/site': typeof AuthenticatedAdminSiteRoute
  '/acting/projects/$slug': typeof ActingProjectsSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/reset-password': typeof ResetPasswordRoute
  '/acting/$section': typeof ActingSectionRoute
  '/acting/profile': typeof ActingProfileRoute
  '/photography/$section': typeof PhotographySectionRoute
  '/acting': typeof ActingIndexRoute
  '/photography': typeof PhotographyIndexRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/site': typeof AuthenticatedAdminSiteRoute
  '/acting/projects/$slug': typeof ActingProjectsSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/acting': typeof ActingRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/photography': typeof PhotographyRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/acting/$section': typeof ActingSectionRoute
  '/acting/profile': typeof ActingProfileRoute
  '/photography/$section': typeof PhotographySectionRoute
  '/acting/': typeof ActingIndexRoute
  '/photography/': typeof PhotographyIndexRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/_authenticated/admin/site': typeof AuthenticatedAdminSiteRoute
  '/acting/projects/$slug': typeof ActingProjectsSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acting'
    | '/auth'
    | '/contact'
    | '/photography'
    | '/reset-password'
    | '/admin'
    | '/acting/$section'
    | '/acting/profile'
    | '/photography/$section'
    | '/acting/'
    | '/photography/'
    | '/admin/media'
    | '/admin/projects'
    | '/admin/site'
    | '/acting/projects/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/reset-password'
    | '/acting/$section'
    | '/acting/profile'
    | '/photography/$section'
    | '/acting'
    | '/photography'
    | '/admin/media'
    | '/admin/projects'
    | '/admin/site'
    | '/acting/projects/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/acting'
    | '/auth'
    | '/contact'
    | '/photography'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/acting/$section'
    | '/acting/profile'
    | '/photography/$section'
    | '/acting/'
    | '/photography/'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/projects'
    | '/_authenticated/admin/site'
    | '/acting/projects/$slug'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ActingRoute: typeof ActingRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  PhotographyRoute: typeof PhotographyRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photography': {
      id: '/photography'
      path: '/photography'
      fullPath: '/photography'
      preLoaderRoute: typeof PhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acting': {
      id: '/acting'
      path: '/acting'
      fullPath: '/acting'
      preLoaderRoute: typeof ActingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photography/': {
      id: '/photography/'
      path: '/'
      fullPath: '/photography/'
      preLoaderRoute: typeof PhotographyIndexRouteImport
      parentRoute: typeof PhotographyRoute
    }
    '/acting/': {
      id: '/acting/'
      path: '/'
      fullPath: '/acting/'
      preLoaderRoute: typeof ActingIndexRouteImport
      parentRoute: typeof ActingRoute
    }
    '/photography/$section': {
      id: '/photography/$section'
      path: '/$section'
      fullPath: '/photography/$section'
      preLoaderRoute: typeof PhotographySectionRouteImport
      parentRoute: typeof PhotographyRoute
    }
    '/acting/profile': {
      id: '/acting/profile'
      path: '/profile'
      fullPath: '/acting/profile'
      preLoaderRoute: typeof ActingProfileRouteImport
      parentRoute: typeof ActingRoute
    }
    '/acting/$section': {
      id: '/acting/$section'
      path: '/$section'
      fullPath: '/acting/$section'
      preLoaderRoute: typeof ActingSectionRouteImport
      parentRoute: typeof ActingRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/acting/projects/$slug': {
      id: '/acting/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/acting/projects/$slug'
      preLoaderRoute: typeof ActingProjectsSlugRouteImport
      parentRoute: typeof ActingRoute
    }
    '/_authenticated/admin/site': {
      id: '/_authenticated/admin/site'
      path: '/site'
      fullPath: '/admin/site'
      preLoaderRoute: typeof AuthenticatedAdminSiteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/projects': {
      id: '/_authenticated/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthenticatedAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminProjectsRoute: typeof AuthenticatedAdminProjectsRoute
  AuthenticatedAdminSiteRoute: typeof AuthenticatedAdminSiteRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminProjectsRoute: AuthenticatedAdminProjectsRoute,
  AuthenticatedAdminSiteRoute: AuthenticatedAdminSiteRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ActingRouteChildren {
  ActingSectionRoute: typeof ActingSectionRoute
  ActingProfileRoute: typeof ActingProfileRoute
  ActingIndexRoute: typeof ActingIndexRoute
  ActingProjectsSlugRoute: typeof ActingProjectsSlugRoute
}

const ActingRouteChildren: ActingRouteChildren = {
  ActingSectionRoute: ActingSectionRoute,
  ActingProfileRoute: ActingProfileRoute,
  ActingIndexRoute: ActingIndexRoute,
  ActingProjectsSlugRoute: ActingProjectsSlugRoute,
}

const ActingRouteWithChildren =
  ActingRoute._addFileChildren(ActingRouteChildren)

interface PhotographyRouteChildren {
  PhotographySectionRoute: typeof PhotographySectionRoute
  PhotographyIndexRoute: typeof PhotographyIndexRoute
}

const PhotographyRouteChildren: PhotographyRouteChildren = {
  PhotographySectionRoute: PhotographySectionRoute,
  PhotographyIndexRoute: PhotographyIndexRoute,
}

const PhotographyRouteWithChildren = PhotographyRoute._addFileChildren(
  PhotographyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ActingRoute: ActingRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  PhotographyRoute: PhotographyRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
